### PR TITLE
[ENG-1598] feat: proxy-only installation should show option to uninstall

### PR DESCRIPTION
**Pull request by jatinsandilya**
This PR adds a button to uninstall the installation for a proxy only integration.

Screenshot 2024-10-29 at 5 30 04 PM

### CODE REVIEW

**Comment by laurenzlong** [comment]
@jatinsandilya can you do something to make it look more clickable? Maybe underline? @AndrewNoNumbers feel free to chime in here with suggestions.

**Comment by jatinsandilya** [comment]
> @jatinsandilya can you do something to make it look more clickable? Maybe underline? @AndrewNoNumbers feel free to chime in here with suggestions.

@laurenzlong this is how it looks on hover. I tried changing it to the `danger` variant but that seemed to take a lot of attention away from the success message. Happy to tweak the design, very open to suggestions here!  

Screenshot 2024-10-30 at 10 01 15 PM

**Comment by AndrewNoNumbers** [comment]
@jatinsandilya Hi Jatin! The button where the background is filled only hover is the Tertiary Button style. Is it possible to make it a Secondary Button (which has a stroke around it)?
https://www.figma.com/design/sBbeJCAqMVaH8vYZpXwWBC/Simple-UI-For-Ampersand?node-id=233-4792&node-type=frame&t=nycJ11k3DXaGClUl-11

That would also make it more consistent to the [non-proxy installation confirmation screen](https://www.figma.com/design/iIWhKDSC3BekQw0yQyXwKz/Builder-UI-Library?node-id=652-5265&node-type=frame&t=c8EpZpiy4A4nYNp5-11).

**Review by dionlow — CHANGES_REQUESTED** [review]
I created a commit on top of this PR to help debug the rendering issue. Listed some feedback on refactoring and moving the CTA component closer to the proxy logic. 

https://github.com/amp-labs/react/pull/662

**Comment by jatinsandilya** [comment]
Updated the design to look like this now @AndrewNoNumbers @dionlow: 

Screenshot 2024-11-01 at 6 30 25 PM

**Comment by jatinsandilya** [comment]
> I created a commit on top of this PR to help debug the rendering issue. Listed some feedback on refactoring and moving the CTA component closer to the proxy logic.
> 
> #662

@dionlow updated the PR with the requested changes. Lmk what you think?

**Comment by laurenzlong** [comment]
@dionlow ping on this.

**Review by dionlow — APPROVED** [review]
LGTM, nice work!

**Pull request merged**
